#!/usr/bin/env python

"""Omnifocus to Kanban

Usage:
  of-to-kb.py (--trello | --leankit | --kanbanflow) [--eval]
  of-to-kb.py -h | --help
  of-to-kb.py --version

"""
import sys
import os
import logging
import logging.config
from timeit import default_timer as timer
from docopt import docopt
from kanban_board import KanbanFlow
from omnifocus import Omnifocus


def main():
    start = timer()

    opts = docopt(__doc__)

    if opts['--kanbanflow']:
        logging.debug("Connecting to KanbanFlow board")
        board = KanbanFlow()
    else:
        raise ValueError("Expected --kanbanflow")

    external_ids = board.find_completed_card_ids()
    
    omnifocus = Omnifocus()

    if not opts['--eval']:
        tasks_closed, repeating_tasks_closed = omnifocus.close_tasks(external_ids)
        # DEBUG tasks_closed, repeating_tasks_closed = [], []
        cards_to_add = omnifocus.flagged_tasks().values()
        board.remove_comments_from_repeating_tasks(repeating_tasks_closed)
        cards_added = board.add_cards(cards_to_add)
        elapsed_time = timer() - start
        result = "{0} update(s), {1} task(s) closed & {2} repeating tasks closed in {3}s".\
            format(cards_added, len(tasks_closed), len(repeating_tasks_closed), round(elapsed_time, 2))
        logging.debug(result)
    else:
        result = "To close: {0}".format(external_ids)
        cards_to_add = omnifocus.flagged_tasks().values()
        result = result + "\n" + "To add: {0}".format(cards_to_add)

    print(result)


if __name__ == '__main__':
    logging.config.fileConfig('./config/log.conf')
    logging.debug("sys.path: %s", sys.path)
    logging.debug("sys.executable: %s", sys.executable)
    logging.debug("os.getcwd(): %s", os.getcwd())

    try:
        main()
    except ValueError as e:
        print("Something's not right\n", e)
        import traceback
        traceback.print_exc()
        sys.exit(-1)
    except IOError as e:
        print("Failed to connect to kanban board", e)
        sys.exit(-1)
